railsapp/config/routes.rb
Rails.application.routes.draw do
  get 'orders/checkout1'
  post 'orders/checkout2'
  get 'orders/n-in-cart'
  get 'orders/history'
  get 'orders/of-children', to: 'orders#index_of_children'
  get 'products/picture' # code=0000&suffix=main
  get 'tags/picture' # code=0000
  get 'messages/by-users', to: 'messages#index_by_users'

  resources :orders
  resources :products
  resources :tags
  resources :messages
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  get 'pages/dashboard'
  get 'pages/dashboard-count' => 'pages#dashboard_count'
  get 'pages/users'
  get 'pages/sign-in-as' => 'pages#sign_in_as', as: :sign_in_as
  root to: 'pages#root'

  get 'pos' => 'products#pos', as: :pos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

railsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "360 Base" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to " &nbsp;&nbsp;&nbsp; ".html_safe, root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "<span class='fa fa-shopping-cart'></span> <span id='n-in-cart' class='badge'>0</span>".html_safe, orders_path %></li>
              <li><%= link_to ("<span class='fa fa-user'></span> "+current_user.name).html_safe, pages_dashboard_path %></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="glyphicon glyphicon-log-out"></i><%= " " + t("Sign out") %>
                  <% end %>
              </li>
            <% else %>
              <li><%= link_to new_user_session_path, method: :get do %>
                  <i class="glyphicon glyphicon-log-in"></i><%= " " + t("Sign in") %>
                  <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
          <p>&nbsp;</p>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Links</h3>
            <ul class="nav nav-list">
              <li class="nav-header"><%= t("Suppliers") %></li>
              <% MAKERS.each do |k,v| %>
                <li><%= link_to v[:name], v[:url], target: k %></li>
              <% end %>
              <li class="nav-header"><%= t("360") %></li>
              <li><%= link_to "360 Dojos", "https://dojo.lmlab.net", target: "_blank" %></li>
              <li><%= link_to "360 Places", "https://places.lmlab.net", target: "_blank" %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; <a href="https://lmlab.net" target="_blank">Lmlab.net</a> 2018</p>
      </footer>

    </div> <!-- /container -->
    <script>
    $("#n-in-cart").load("/orders/n-in-cart");
    </script>
  </body>
</html>