railsapp/config/routes.rb
Rails.application.routes.draw do
  get 'orders/checkout1'
  post 'orders/checkout2'
  get 'orders/n-in-cart'
  get 'orders/history'
  get 'orders/of-children', to: 'orders#index_of_children'
  get 'products/picture' # code=0000&suffix=main
  get 'tags/picture' # code=0000
  get 'messages/by-users', to: 'messages#index_by_users'

  resources :orders
  resources :products
  resources :tags
  resources :messages
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  get 'pages/dashboard'
  get 'pages/dashboard-count' => 'pages#dashboard_count'
  get 'pages/users'
  get 'pages/sign-in-as' => 'pages#sign_in_as', as: :sign_in_as
  root to: 'pages#root'

  get 'pos' => 'products#pos', as: :pos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

railsapp/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_paper_trail

  scope :in_cart, -> { where(status: "in-cart") }
  scope :ordered, -> { where(status: "ordered") }
  scope :shipping, -> { where(status: "shipping") }
  scope :arrived, -> { where(status: "arrived") }
  scope :canceled, -> { where(status: "canceled") }

  def self.total(orders)
    # tax should be included in each price
    total = 0
    orders.each {|o| total += o.price * o.quantity}
    return total
  end
end

railsapp/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /orders
  # GET /orders.json
  def index
    ts = params[:checkout_at]
    if ts.nil?
      @checkout_at = nil
      @orders = current_user.orders.in_cart
      @removable = true
    else
      u = User.find(params[:user_id]) if params[:user_id]
      u = current_user unless u
      @checkout_at = Time.parse(ts)
      @orders = u.orders.where(checkout_at: @checkout_at)
    end
  end

  def index_of_children
    status = params[:status]
    # 自分の子どものordersでstatusがorderedの商品(商品ごと)
    # 自分の子どものordersでstatusがshippingの商品(ユーザごと)
    @checkout_at = nil
    children = current_user.users4order
    if status == "ordered"
      @title = "orders_of_children"
      @orders = Order.ordered.where(user_id: children.map { |c| c.id })
      if @orders.count == 0
        @orders = nil
      elsif params[:group_by_product]
        @orders = @orders.group(:product_id).select("product_id, sum(quantity) as quantity")
      end
    elsif status == "shipping"
      @title = "shipping_of_children"
      @orders = Order.shipping.where(user_id: children.map { |c| c.id })
      if @orders.count == 0
        @orders = nil
      elsif params[:group_by_product]
        @orders = @orders.group(:product_id).select("product_id, sum(quantity) as quantity")
      end
    end
    respond_to do |format|
      format.html
      format.csv
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id if @order.user_id == 0
    @order.price = @order.product.price
    another_order = current_user.orders.in_cart.where(product_id: @order.product_id).first
    logger.debug("----------------#{@order.price}..........")
    if another_order
      another_order.quantity += @order.quantity
      another_order.price += (@order.quantity*@order.price)
      logger.debug("----------------#{@order.price}..........")
      @order = another_order
    end
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: t('Order was successfully created') }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: t('Order was successfully updated') }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    if @order.status == "in-cart"
      @order.destroy
      m = 'Order was successfully destroyed'
    else
      m = 'can not destoy'
    end
    respond_to do |format|
      format.html { redirect_to orders_url, notice: t(m) }
      format.json { head :no_content }
    end
  end

  def checkout1
    @orders = current_user.orders.in_cart
    # FIXME: 一時的にstripeは無効化(手数料・送料の問題があるため)
    @use_stripe = false  # current_user.parent&.admin?
  end

  def checkout2
    u = current_user
    orders = u.orders.in_cart
    ts = Time.now
    @n_items = 0
    orders.each do |o|
      @n_items += o.quantity
      o.checkout_at = ts
      o.status = "ordered"
      o.save
    end
    @checkout_at = ts
    @total = Order.total(orders)
    stripe(@total) if params[:stripeToken]
    SlackJob.perform_now("#{u.name}様(id:#{u.id})の注文が確定されました。\n#{ts}, #{@n_items}\nhttps://base.lmlab.net")
    Mailer.simple(nil,u.email,'注文確定','注文が確定されました。').deliver
    # TODO: Need some more info for the customer.

    pid = u.parent&.paypal_id
    t = (@total * 1.036 + 40).to_i
    @paypalme_url = "https://www.paypal.me/#{pid}/#{t}jpy" if pid.present?
  end

  def history
    if params[:children]
      @title = "history_of_children"
      @orders = current_user.checkout_histories_of_children
    else
      @title = "history"
      @orders = current_user.checkout_histories
    end
  end

  def n_in_cart
    render plain: "#{current_user.orders.in_cart.count}"
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:user_id, :checkout_at, :product_id, :quantity, :status, :price)
  end

  def stripe(total)
    # Token is created using Checkout or Elements!
    # Get the payment token ID submitted by the form:
    token = params[:stripeToken]

    charge = Stripe::Charge.create({
        amount: total,
        currency: 'jpy',
        description: 'Example charge',
        source: token,
    })
  end
end

railsapp/app/helpers/orders_helper.rb
module OrdersHelper
end

railsapp/app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

railsapp/app/views/orders/_stripe.html.erb
<form action="checkout2" method="post">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_DfoKFBIrAGKhxBbDgP0G954e"
    data-amount="<%= total %>"
    data-name="LumberMill"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-currency="jpy">
  </script>
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token"/>
</form>

railsapp/app/views/orders/checkout.html.erb
<%- model_class = Order -%>
<script>
$.ajaxSetup({
  headers: {
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  }
});

function remove_from_cart(order_id,b){
  var tr = b.parentNode.parentNode;
  $(tr).fadeOut();
  $("#total").fadeOut();
  $.ajax({url:"/orders/"+order_id+".json", type: "delete"})
    .done(function(d){
      console.log(d);
      var sum = 0;
      $(tr).remove();
      $(".subtotal").each(function(){
        sum += Number($(this).text());
      });
      $("#total").text(sum).fadeIn();
      $("#n-in-cart").load("/orders/n-in-cart");
    })
    .fail(function(d){
      alert("Can not process the order.");
    });
}
</script>
<div class="page-header">
  <h1><span class="fa fa-credit-card"></span> Checkout</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% if @orders.count == 0 %>
      <tr>
        <td colspan="6">Cart is empty.</td>
      </tr>
    <% else
         total = 0
         @orders.each do |order| %>
      <tr>
        <td><%= link_to image_tag(order.product.picture_path, style: "max-height: 64px"), product_path(order.product) %></td>
        <td><%= order.product.name %> <small class="text-muted"><%= order.product.code %></small></td>
        <td><%= order.product.price %></td>
        <td><%= order.amount %></td>
        <td class="subtotal"><%= order.product.price * order.amount %></td>
      </tr>
      <% end
       end %>
    <tr>
      <th colspan="4" style="text-aling: right">Total:</td>
      <td colspan="1" id="total"><%= total %></td>
    </tr>
  </tbody>
</table>

<% if @orders.count == 0 %>
  <button class="btn btn-primary" disabled="disabled">Place the order</button>
<% else %>
  <%= link_to 'Place the order', orders_checkout_path, class: 'btn btn-primary' %>
  <%= link_to 'Back', orders_path, class: 'btn btn-default' %>
<% end %>

railsapp/app/views/orders/checkout1.html.erb
<%- model_class = Order -%>
<script>
$.ajaxSetup({
  headers: {
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  }
});

function remove_from_cart(order_id,b){
  var tr = b.parentNode.parentNode;
  $(tr).fadeOut();
  $("#total").fadeOut();
  $.ajax({url:"/orders/"+order_id+".json", type: "delete"})
    .done(function(d){
      console.log(d);
      var sum = 0;
      $(tr).remove();
      $(".subtotal").each(function(){
        sum += Number($(this).text());
      });
      $("#total").text(sum).fadeIn();
      $("#n-in-cart").load("/orders/n-in-cart");
    })
    .fail(function(d){
      alert("Can not process the order.");
    });
}
</script>
<div class="page-header">
  <h1><span class="fa fa-credit-card"></span><%= t("Confirm Checkout") %></h1>
</div>
<div class="alert alert-warning">
  まだ注文は確定していません。
  再度内容をご確認の上、最下部の「注文を確定する」ボタンを押してください。
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("Picture") %></th>
      <th><%= t("Name") %></th>
      <th><%= t("Price") %></th>
      <th><%= t("Quantity") %></th>
      <th><%= t("Subtotal") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @orders.count == 0 %>
      <tr>
        <td colspan="6">Cart is empty.</td>
      </tr>
    <% else
         total = 0
         @orders.each do |order| %>
      <tr>
        <td><%= link_to image_tag(order.product.picture_path, style: "max-height: 64px"), product_path(order.product) %></td>
        <td><%= order.product.name %>
          <%= order.product.size %>
          <small class="text-muted"><%= order.product.code %></small></td>
        <td><%= order.product.price %></td>
        <td><%= order.quantity %></td>
        <td class="subtotal"><%= order.product.price * order.quantity %></td>
      </tr>
      <% total += order.product.price * order.quantity %>
      <% end
       end %>
    <tr>
      <th colspan="4" style="text-aling: right"><%= t("Total") +":" %></th>
      <td colspan="1" id="total"><%= total %></td>
    </tr>
  </tbody>
</table>

<% if @orders.count == 0 %>
  <button class="btn btn-primary" disabled="disabled"><%= t("Place the order") %></button>
<% elsif @use_stripe %>
  <%= render "stripe", { total: total } %>
  <br/>
<% else %>
  <%= link_to t('Place the order'), orders_checkout2_path, method: :post, class: 'btn btn-primary' %>
<% end %>
<%= link_to t('Back'), orders_path, class: 'btn btn-default' %>

railsapp/app/views/orders/checkout2.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><span class="fa fa-credit-card"></span><%= t("Checkout") %></h1>
</div>
<p><%= t("order_sent") %></p>
<div class="well">
  <p>注文日時: <%= l @checkout_at %>, 点数: <%= @n_items %>, 合計金額: <%= @total %></p>
  <p>ディストリビュータからのメッセージ:<br/><%= sanitize_message(current_user.parent&.message4payment) %></p>

</div>
<% if @paypalme_url %>
  <p>以下のリンクからPayPal経由でお支払い頂くことも可能です。
    このシステムでは送料を加算していませんので、支払い後すぐに商品が届く訳ではありません。
  ディストリビュータとの商品受け渡し手順が確定している場合のみ、ご利用ください。
  Paypalの利用手数料(3.6% + 40円)が加算されています。</p>
  <p><%= link_to @paypalme_url, @paypalme_url, target: "_blank" %> </p>
<% end %>
<% if params[:stripeToken] %>
  <p>Stripeで決済処理を開始致しました。</p>
  <%# エラー処理が未実装なので、ちょっとぼかした文言にしています %>
<% end %>

<p><%= link_to t("back"), pages_dashboard_path, class: "btn btn-default" %></p>

railsapp/app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

railsapp/app/views/orders/history.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><span class="fa fa-shopping-cart"></span> <%= t(@title) %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("datetime") %></th>
      <th><%= t("user_id") if @title == "history_of_children"  %></th>
      <th><%= t("status") %></th>
      <th><%= t("quantity") %></th>
      <th><%= t("price") %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @orders.length == 0 %>
      <tr>
        <td colspan="5"><%= t("No orders") %></td>
      </tr>
    <% else
         total = 0
         @orders.each do |order|
           style_status = ""
           style_checkout_at = ""
           if ["shipping","ordered"].include? order.status
             style_status = "font-weight: bold"
             if order.checkout_at < (Time.now - 7.days)
               style_checkout_at = "color: red"
             end
           end
    %>
      <tr>
        <td style="<%= style_checkout_at %>"><%= l(order.checkout_at) %></td>
        <td><%= order.user.name if @title == "history_of_children" %></td>
        <td style="<%= style_status %>"><%= t(order.status) %></td>
        <td><%= order.quantity %></td>
        <td><%= order.price %></td>
        <% if @title == "history_of_children" %>
          <td><%= link_to t("detail"), orders_path(checkout_at: order.checkout_at,user_id: order.user.id), class: "btn btn-default btn-sm" %></td>
        <% else %>
          <td><%= link_to t("detail"), orders_path(checkout_at: order.checkout_at), class: "btn btn-default btn-sm" %></td>
        <% end %>
      </tr>
      <% end
       end %>
  </tbody>
</table>
<% if @title == "history_of_children" %>
<p><%= link_to '自分自身の注文履歴', orders_history_path, class: "btn btn-default" %></p>
<% elsif current_user.children.count > 0 %>
<p><%= link_to 'フロントの注文履歴', orders_history_path(children: true), class: "btn btn-default" %></p>
<% end %>
<ul class="text-muted">
  <li>注文後 <%= 7 %> 日経過すると日時が赤字で表示されます。ディストリビュータに状況を確認してください。</li>
</ul>

railsapp/app/views/orders/index.html.erb
<%- model_class = Order -%>
<script>
$.ajaxSetup({
  headers: {
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  }
});

function remove_from_cart(order_id,b){
  var tr = b.parentNode.parentNode;
  $(tr).fadeOut();
  $("#total").fadeOut();
  $.ajax({url:"/orders/"+order_id+".json", type: "delete"})
    .done(function(d){
      console.log(d);
      var sum = 0;
      $(tr).remove();
      $(".subtotal").each(function(){
        sum += Number($(this).text());
      });
      $("#total").text(sum).fadeIn();
      $("#n-in-cart").load("/orders/n-in-cart");
    })
    .fail(function(d){
      alert("<%= t("Can not process the order.") %>");
    });
}
</script>
<div class="page-header">
  <% if @checkout_at %>
    <h1><span class="fa fa-shopping-cart"></span> <%= t("Order") %></h1>
    <p><%= l(@checkout_at) %> <%= t(@orders.first.status) %>
      <% if params[:user_id] %>
      <%= link_to t("back"), orders_history_path(children: true), class: "btn btn-default btn-sm" %>
      <% else %>
      <%= link_to t("back"), orders_history_path, class: "btn btn-default btn-sm" %>
      <% end %>
    </p>
  <% else %>
    <h1><span class="fa fa-shopping-cart"></span> <%= t("Cart") %></h1>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("Picture") %></th>
      <th><%= t("Name") %></th>
      <th><%= t("Price") %></th>
      <th><%= t("Quantity") %></th>
      <th><%= t("Subtotal") %></th>
      <% if @removable %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if @orders.count == 0 %>
      <tr>
        <td colspan="6"><%= t("Cart is empty") %></td>
      </tr>
    <% else
         total = 0
         @orders.each do |order| %>
      <tr>
        <td><%= link_to image_tag(order.product.picture_path, style: "max-height: 64px"), product_path(order.product) %></td>
        <td><%= order.product.name %>
          <%= order.product.size %>
          <small class="text-muted"><%= order.product.code %></small></td>
        <td><%= order.product.price %></td>
        <td><%= order.quantity %></td>
        <td class="subtotal"><%= order.product.price * order.quantity %></td>
        <% if @removable %>
          <td><%= link_to t("Remove"), "javascript:void(0)", onclick: "remove_from_cart(#{order.id},this)", class: "btn btn-default btn-xs" %></td>
        <% end %>
        <% total += order.product.price * order.quantity %>
      </tr>
      <% end
       end %>
    <tr>
      <th colspan="4" style="text-aling: right"><%= t("Total") +":" %></th>
      <td colspan="2" id="total"><%= total %></td>
    </tr>
  </tbody>
</table>

<% if @checkout_at %>
<% elsif @orders.count == 0 %>
  <button class="btn btn-primary" disabled="disabled"><%= t("Proceed to checkout") %></button>
<% else %>
  <%= link_to t('Proceed to checkout'), orders_checkout1_path, class: 'btn btn-primary' %>
<% end %>
  <%= link_to t("Back to dashboard"), pages_dashboard_path, class: "btn btn-default" %>

railsapp/app/views/orders/index_of_children.csv.erb
<%# 作りかけです。必要になってから整形します %>
<% total = 0 %>
<% if params[:group_by_product] %>
<% @orders.each do |order| %>
<%= order.product_id %>
<%= order.product.name %>
<%= order.product.code %>
<%= order.product.price %>
<%= order.quantity %>
<%= order.product.price * order.quantity %>
<% end %>
<% else %>
<% @orders.each do |order| %>
<%= order.id %>
<%= order.user.name %>
<%= order.updated_at %>
<%= order.product.name %>
<%= order.product.code %>
<%= order.product.price %>
<%= order.quantity %>
<%= order.product.price * order.quantity %>
<% end %>
<% end %>

railsapp/app/views/orders/index_of_children.html.erb
<%- model_class = Order -%>
<script>
$.ajaxSetup({
  headers: {
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  }
});

function update_order_status(status){
  $("#total").fadeOut();
  $("input[name=orders]:checked").each(function(){
      var order_id = $(this).val();
      if(!order_id) return;
      var tr = $("#row-"+order_id);
      $(tr).fadeOut();
      $.ajax({url:"/orders/"+order_id+".json",type: "patch",
        data: {"order[id]": order_id, "order[status]": status}})
        .done(function(d){
          console.log(d);
          var sum = 0;
          $(tr).remove();
          $(".subtotal").each(function(){
            sum += Number($(this).text());
          });
          $("#total").text(sum).fadeIn();
        })
        .fail(function(d){
          alert("<%= "Can not change status of order." %>");
        });
  });
}

function update_group_by_product(){
  $("#group_by_product_form").submit();
}

$(function(){
  $("#group_by_product").on('change',update_group_by_product);
});
</script>
<div class="page-header">
  <h1><span class="fa fa-list"></span> <%= t(@title) %></h1>
</div>
<form action="of-children" method="get" id="group_by_product_form">
  <%= check_box_tag :group_by_product, "true", params[:group_by_product].present?  %>
  <%= hidden_field_tag :status, params[:status] %>
  <label for="group_by_product">商品ごとにグルーピングする</label>
</form>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("User Name") %></th>
      <th><%= t("Updated date") %></th>
      <th><%= t("Picture") %></th>
      <th><%= t("Name") %></th>
      <th><%= t("Price") %></th>
      <th><%= t("Quantity") %></th>
      <th><%= t("Subtotal") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% n, total_price, total_quantity = 0, 0, 0 %>
    <% if @orders.nil? %>
      <tr>
        <td colspan="7"><%= t("Nothing to show here") %></td>
      </tr>
    <% elsif params[:group_by_product] %>
      <% @orders.each do |order| %>
        <tr id="row-<%= order.product_id %>">
          <td></td>
          <td></td>
          <td><%= link_to image_tag(order.product.picture_path, style: "max-height: 64px"), product_path(order.product) %></td>
          <td><%= order.product.name %> <small class="text-muted"><%= order.product.code %></small></td>
          <td><%= order.product.price %></td>
          <td><%= order.quantity %></td>
          <td class="subtotal"><%= order.product.price * order.quantity %></td>
          <td></td>
          <% n += 1 %>
          <% total_quantity += order.quantity %>
          <% total_price += order.product.price * order.quantity %>
        </tr>
      <% end %>
      <tr>
        <th colspan="3" style="text-aling: right"><%= t("Total") +":" %></th>
        <td colspan="2" class="text-muted"><%= 0 %>人, <%= n %>品目</td>
        <td><%= total_quantity %></td>
        <td colspan="2" id="total"><%= total_price %></td>
      </tr>
    <% else
        # List of orders
         @orders.each do |order| %>
      <tr id="row-<%= order.id %>">
        <td><%= order.user.name %></td>
        <td><%= order.updated_at %></td>
        <td><%= link_to image_tag(order.product.picture_path, style: "max-height: 64px"), product_path(order.product) %></td>
        <td><%= order.product.name %> <small class="text-muted"><%= order.product.code %></small></td>
        <td><%= order.product.price %></td>
        <td><%= order.quantity %></td>
        <td class="subtotal"><%= order.product.price * order.quantity %></td>
        <td><%= check_box_tag :orders, order.id %></td>
        <% total_price += order.product.price * order.quantity %>
      </tr>
      <% end %>
      <tr>
        <th colspan="6" style="text-aling: right"><%= t("Total") +":" %></th>
        <td colspan="2" id="total"><%= total_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="message">

</div>
<% if params[:group_by_product].present? %>
  <p>グルーピングされたまま、「発注済み」「納品済み」に移行できません。解除してから入力してください。</p>
<% elsif @title == "orders_of_children" %>
  <p>
    あなたのフロントからの注文と、あなた自身の注文がリストアップされています。<br/>
    <a href="https://www.amwaylive.com/">Amwaylive</a>で発注した商品にチェックを入れてください。</p>
  <button class='btn btn-primary' onclick="update_order_status('shipping')"><%= t("mark_as_shipping") %></button>
<% elsif @title == "shipping_of_children" %>
  <p>お客様に手渡しした（または自分で受け取った）商品にチェックを入れてください。</p>
  <button class='btn btn-primary' onclick="update_order_status('arrived')"><%= t("mark_as_arrived") %></button>
<% end %>

railsapp/app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

railsapp/app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @order.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:checkout_at) %>:</strong></dt>
  <dd><%= @order.checkout_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @order.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @order.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @order.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @order.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>