railsapp/config/routes.rb
Rails.application.routes.draw do
  get 'orders/checkout1'
  post 'orders/checkout2'
  get 'orders/n-in-cart'
  get 'orders/history'
  get 'orders/of-children', to: 'orders#index_of_children'
  get 'products/picture' # code=0000&suffix=main
  get 'tags/picture' # code=0000
  get 'messages/by-users', to: 'messages#index_by_users'

  resources :orders
  resources :products
  resources :tags
  resources :messages
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  get 'pages/dashboard'
  get 'pages/dashboard-count' => 'pages#dashboard_count'
  get 'pages/users'
  get 'pages/sign-in-as' => 'pages#sign_in_as', as: :sign_in_as
  root to: 'pages#root'

  get 'pos' => 'products#pos', as: :pos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

railsapp/app/views/pages/about.html.erb
<h1><%= t("about") %></h1>
<p>Find me in app/views/pages/about.html.erb </p>

railsapp/app/views/pages/dashboard.html.erb
<div class="row">
  <div class="col-xs-12">
    <p><%= t("hello") %> <b><%= current_user.name %></b> さん!
      <%= link_to ("<span class='fa fa-user'></span> "+t("edit_user")).html_safe, edit_user_registration_path, class: "btn btn-xs btn-default" %>
    </p>
    <p>下記の検索フィールドにお探しの商品名か商品コードを入力してください。</p>
  </div>
</div>
<div class="row" style="padding: 60px 0;">
  <div class="col-xs-12 col-sm-8">
    <form method="get" action="<%= products_path %>" class="form-inline search">
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: t("name,code or tag:name"), size: 60 %>
      <%= button_tag ('<span class="fa fa-search"></span> '.+t('search')).html_safe, class: 'btn btn-primary ' %>
    </form>
    <%= makers_as_list %>
  </div>
</div>
<h3><%= t("category") %></h3>
<div class="row">
  <% @tags.each do |tag| %>
    <div class="col-sm-4 col-md-2">
      <figure>
        <%= link_to image_tag(tag.picture_path, class: "img-thumbnail"), products_path(search: "tag:"+tag.code) %>
        <figcaption><%= tag.name %> <span class="text-muted" id="n-tag-<%= tag.code %>"></span></figcaption>
      </figure>
    </div>
  <% end %>
</div>
<h3><%= t("recent_view") %></h3>
<div class="row" style="padding: 24px 0">
  <% @recent_views.each do |recent| %>
    <div class="col-sm-3">
      <figure>
        <%= link_to image_tag(recent.product.picture_path, class: "img-thumbnail img-responsive"), product_path(recent.product) %>
        <figcaption><%= recent.product.name %></figcaption>
      </figure>
    </div>
  <% end %>
</div>
<h3><%= t("recent_order") %></h3>
<div class="row" style="padding: 24px 0">
  <% @recent_orders.each do |product| %>
    <div class="col-sm-3">
      <figure>
        <%= link_to image_tag(product.picture_path, class: "img-thumbnail img-responsive"), product_path(product) %>
        <figcaption><%= product.name %></figcaption>
      </figure>
    </div>
  <% end %>
</div>

<div class="row" style="padding: 24px 0">
  <div class="col-sm-12">
    <p>
    <%= link_to ("<span class='fa fa-list'></span> "+t("order_history") + " <span class='badge' id='orders'>-</span>").html_safe, orders_history_path, class: "btn btn-default" %>
    <%= link_to "<span class='fa fa-slack'></span> ".html_safe+"チャットルーム", "https://360cw.slack.com/messages/CD34HGR6D/", class: "btn btn-default", target: "_blank" %>
    <% if current_user.parent %>
      <%= link_to "<span class='fa fa-paper-plane'></span> ".html_safe+"お問い合わせ", messages_path, class: "btn btn-default" %>
      <small> あなたのディストリビュータは <%= current_user.parent.name %> さんです。</small>
    <% else %>
    <%= link_to "<span class='fa fa-paper-plane'></span> ".html_safe+"お問い合わせ", messages_by_users_path, class: "btn btn-default" %>
      <% if current_user.admin? %>
        <small> 管理ユーザとしてログイン中です。</small>
      <% else %>
        <small style="color: red"> ディストリビュータ不在</small>
      <% end %>
    <% end %>
    </p>
    <p>「こんな商品も扱って欲しい」「こんな使い方がしたい」等のご意見、ご要望を気軽にお寄せください。
      上記「チャットルーム」リンクはSlackのチャネルになっており、別途アカウント登録が必要です。
      アカウントのない方は、「お問い合わせ」から管理者あてにメッセージを送信することが可能です。
    </p>
  </div>
</div>
<script type="text/javascript">
  $("#orders").load("dashboard-count?key=orders");
</script>
<% if current_user.distributor? %>
  <h3><%= t("for_distributor") %></h3>
  <div class="row" style="padding: 24px 0">
    <div class="col-sm-12">
      <p>
      <%= link_to ("<span class='fa fa-shopping-cart'></span> "+t("orders_of_children") + " <span class='badge' id='orders_of_children'>-</span>").html_safe, orders_of_children_path(status: 'ordered'), class: "btn btn-default" %>
      <%= link_to ("<span class='fa fa-truck'></span> "+t("shipping_of_children") + " <span class='badge' id='shipping_of_children'>-</span>").html_safe, orders_of_children_path(status: 'shipping'), class: "btn btn-default" %>
      <%= link_to ("<span class='fa fa-list'></span> "+t("history_of_children")).html_safe, orders_history_path(children: 'true'), class: "btn btn-default" %>
      <%= link_to ("<span class='fa fa-users'></span> "+t("children") + " <span class='badge' id='number_of_children'>-</span>").html_safe, pages_users_path, class: "btn btn-default" %>
      <%= link_to ("<span class='fa fa-calculator'></span> POS").html_safe, pos_path, class: "btn btn-default" %>
      </p>
      <p>新規のユーザに登録してもらう際に、登録者本人のアドレスに加え、あなたのID（メールアドレス）も必要です。
        「<code><%= current_user.email %></code>」をIDとして使用するよう事前に知らせてください。
      </p>
    </div>
  </div>
  <script>
    $("#orders_of_children").load("dashboard-count?key=orders_of_children");
    $("#shipping_of_children").load("dashboard-count?key=shipping_of_children");
    $("#number_of_children").load("dashboard-count?key=number_of_children");
    $("#n-maker-undefined").load("dashboard-count?key=n-maker");
    <% MAKERS.keys.each do |m| %>
    $("#n-maker-<%= m %>").load("dashboard-count?key=n-maker&maker=<%= m %>");
    <% end %>
  </script>
  <p>メッセージ</p>
  <pre><%= current_user.message %></pre>
  <p>注文完了後に表示されるメッセージ <%= link_to "編集", edit_user_registration_path, class: "btn btn-default btn-xs" %></p>
  <pre><%= current_user.message4payment %></pre>
<% end %>
<% if current_user.admin? %>
  <div class="row">
    <div class="col-xs-12 admin">
        <%= link_to ("<span class='fa fa-users'></span> "+t("Users")).html_safe, pages_users_path(all: true), class: "btn btn-default" %>
        <%= link_to ("<span class='fa fa-gift'></span> "+t("Products")).html_safe, products_path(search: ""), class: "btn btn-default" %>
        <%= link_to ("<span class='fa fa-tag'></span> "+t("Tags")).html_safe, tags_path(search: ""), class: "btn btn-default" %>
        <%= link_to "<span class='fa fa-github'></span> GitHub".html_safe, "https://github.com/lumbermill/base.lmlab.net", target: "_blank" %>
    </div>
  </div>
<% end %>

railsapp/app/views/pages/root.html.erb
<div class="page-header">
<h1>360 Base</h1>
</div>
<p>360で販売している商品の受発注サイトです。
  アカウントをお持ちの方は、ログインしてご利用ください。
  新規ユーザ登録の際には、担当ディストリビュータのIDが必要です。予めご確認の上、お手続きください。 </p>

<% if user_signed_in? %>
  <%= link_to '<span class="fa fa-home"></span> '.html_safe+t('Dashboard'), pages_dashboard_path, class: "btn btn-success" %>
<% else %>
  <%= link_to '<span class="fa fa-sign-in"></span> '.html_safe+t('Sign in'), new_user_session_path, class: "btn btn-success" %>
<% end %>
<%= link_to '<span class="fa fa-edit"></span> '.html_safe+t("Sign up"), new_user_registration_path, class: "btn btn-primary" %>

railsapp/app/views/pages/users.html.erb
<h1><%= @all ? t("Users") : t("Fronts") %></h1>
<table class="table">
  <tr>
    <th><%= t("User Name") %></th>
    <th><%= t("Email") %></th>
    <th><%= t("Confirmed") %></th>
    <th><%= t("Distributor") %></th>
    <th><%= t("Last signed in") %></th>
  </tr>
  <% @users.each do |u| %>
  <tr>
    <% if u.id == current_user.id %>
      <td><%= u.name %></td>
    <% else %>
      <td><%= link_to u.name, sign_in_as_path(id: u.id) %></td>
    <% end %>
    <td><%= u.email %></td>
    <td><%= u.confirmed? ? ('<span class="fa fa-check" title="'+u.confirmed_at.to_s+'"></span>').html_safe : "" %></td>
    <td><%= u.distributor? ? ('<span class="fa fa-check" title="'+u.children.count.to_s+'"></span>').html_safe : "" %></td>
    <td><%= u.last_sign_in_at %></td>
  </tr>
  <% end %>
</table>
<ul class="text-muted">
  <li>ユーザ名のリンクをクリックすると、そのユーザとしてログインします。
  ログイン履歴が残りますので、必ず事前に当該ユーザの承諾を得て作業してください。</li>
  <li>フロントが存在するユーザはディストリビュータとして扱われます（あなた宛には発注が計上されなくなります）。</li>
</ul>